# yaml-language-server: $schema=https://raw.githubusercontent.com/Shikachuu/stickerbomb/main/schemas/labeler_v1alpha1.json
apiVersion: stickerbomb.dev/v1alpha1
kind: Labeler
metadata:
  name: label-all-pods
  namespace: default
spec:
  resourceApi: "v1"
  resourceKind: "Pod"
  labels:
    environment: development
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/Shikachuu/stickerbomb/main/schemas/labeler_v1alpha1.json
apiVersion: stickerbomb.dev/v1alpha1
kind: Labeler
metadata:
  name: label-pod-labelers
  namespace: default
spec:
  resourceApi: "stickerbomb.dev/v1alpha1"
  resourceKind: "Labeler"
  labels:
    labeler-target: pod
  rego:
    policy: |
      package stickerbomb

      default allow = false

      allow if {
        input.spec.resourceKind == "Pod"
      }
    query: "data.stickerbomb.allow"
